### ISSUE TITLE
Upgrade `future` requirement

### ISSUE THREAD

**Issue by cmutel** [kislyuk/eight#2]
The latest version of `future` is 0.15.2; maybe it would make sense to upgrade the version in requirements and setup.py? The tests pass without any problems, and presumably the latest version includes some bug fixes... 

If future is included in any dependency chain it will be upgraded by e.g. pip install -U foo, and one has to pay attention and reinstall the pinned version afterwards, which isn't so nice for non-technical people.

**Comment by aignas** [comment]
I agree with @cmutel.

**Comment by kislyuk** [comment]
Released in v0.3.3, please test

**Comment by cardosan** [comment]
While commit cadc665 upgrade the requirement to `future >= 0.16, < 0.17`, in the version on pipy is still`future==0.15.2` and this create conflicts being `future` at the version 0.16 now

**Comment by cmutel** [comment]
For the time being, you can install using:
    
    pip install https://github.com/kislyuk/eight/zipball/master

This will also work in `requirements.txt`. In `setup.py`, use:

    install_requires=['https://github.com/kislyuk/eight/zipball/master#egg=eight-0.3.4.dev0']

**Comment by kislyuk** [comment]
Released master in v0.4.1.
