### ISSUE TITLE
Is eight production ready?

### ISSUE THREAD

**Issue by dhimmel** [kislyuk/eight#6]
I love the motivation behind `eight` -- you can use Python 2 for compatibility but essentially pretend you're writing code in Python 3. If I understand, `eight` means you can write as if you're using Python 3, but still have your code run in 2.

@kislyuk and others, I was wondering whether you deem this package "production ready"? I saw the activity level is rather low on GitHub, but does `eight` generally work reliably or is it more for enthusiasts looking to try out a cool idea?

P.S. @kislyuk I think I may have learned about this package at a SF Python Meetup you spoke at!

**Comment by cmutel** [comment]
What do you mean by "production-ready"? Surely production would be running on one version of Python :) I use this package everywhere that 2/3 compatibility is needed - it works quite well even in complex cases (thought sometimes you have to import stuff `future` directly).

**Comment by kislyuk** [comment]
Thanks for writing @dhimmel and @cmutel. I maintain this package and use it in production. Unless there are good ideas about where to take it from here or issues filed by users, I anticipate it will remain in maintenance mode indefinitely.

**Comment by kislyuk** [comment]
I'm going to close this for now, feel free to comment or open a new issue if you have problems.
